### ISSUE TITLE
希望能够支持 Alt+Enter 快捷键

### ISSUE THREAD

**Issue by pansong291** [TonyPhoneix/genallsetter2kt#2]
我只知道 Win 上的快捷键是 <kbd>Alt</kbd><kbd>Enter</kbd>。Mac 上不知道。

这个快捷键的作用是 `Show Context Actions`。希望能按这个快捷键也能出现相关菜单。

**Comment by vigor-yuan** [comment]
这个主要和你generate快捷键的设置有关，你可以打开keymap 搜索 generate，看一下你的设置是什么就可以了。
下图是我的设置
![image](https://user-images.githubusercontent.com/17443550/118425530-f0ec5a00-b6fb-11eb-9301-7c15a82b2bbf.png)

**Comment by pansong291** [comment]
我的意思是，希望它能出现在 Context Action 菜单里，不只是 Generate 菜单里
