### ISSUE TITLE
希望可以支持识别for (Dto d : list) 里面的d作为get的对象

### ISSUE THREAD

**Issue by TeemoInBush** [TonyPhoneix/genallsetter2kt#3]
for (int i = 0; i < list.size(); i++) {
    Dto d = list.get(i);
这样可以在Generate All Setter With Getter的时候，选择到d，
for (Dto d : list)  {
这样就选择不到了

**Comment by vigor-yuan** [comment]
可以支持的，我这边有空加一下

**Comment by pansong291** [comment]
@TonyPhoneix 还有方法参数上，比如：
```java
private void convert(Source s, Target t) {
    t.setXXX(s.getXXX());
    t.setYYY(s.getYYY());
}
```
如果在函数入参那个地方也能生成就好了。
