### ISSUE TITLE
插件在 IntelliJ IDEA 2024.3 (Ultimate Edition) Build #IU-243.21565.193, built on November 13, 2024 不可用

### ISSUE THREAD

**Issue by NEUguomiaomiao** [TonyPhoneix/genallsetter2kt#6]
你好，能帮忙看下插件在新版本 IDEA 上不可用的问题吗？具体表现在按 command+n 无效。

**Comment by slgithuba** [comment]
我也发现了,新版2024.3找不到选项了

**Comment by vigor-yuan** [comment]
好的，我处理下

**Comment by jounghu** [comment]
> 好的，我处理下

大佬，帮忙加急处理一下，很喜欢这个插件

**Comment by vigor-yuan** [comment]
> > 好的，我处理下
> 
> 大佬，帮忙加急处理一下，很喜欢这个插件

新版本已经发布到release页了，可以下载后手动安装，从市场下载还需要等两个工作日
