### ISSUE TITLE
大佬,有个小小的需求,期待加入一键生成所有的getter方法的功能

### ISSUE THREAD

**Issue by slgithuba** [TonyPhoneix/genallsetter2kt#8]
大佬,有个小小的需求,该插件里面都是围绕setter方法进行赋值,能否加入一键生成所有的getter方法的功能,有时候需要打印类中所有的属性,这个用的不多,偶尔会使用到,如果不麻烦的话期待加入一下,这样的话就吊打所有的转换了. 另外这个插件简洁好用,一直在用这个,👍🏻

**Comment by vigor-yuan** [comment]
好的，我加一下

**Comment by slgithuba** [comment]
多谢大佬

**Comment by vigor-yuan** [comment]
一键生成所有getter方法的功能已经更新在v2.0.5版本，已上架插件市场。呼出Generate菜单会有`invoke all getter` 选项，

![image](https://github.com/user-attachments/assets/b154fecb-59fe-46cc-b9c7-0f60234631aa)
